### ISSUE TITLE
Release with wheel?

### ISSUE THREAD

**Issue by jensens** [zopefoundation/zope.globalrequest#12]
Currently the package is released as Source Distribution only on PyPI. It would be good to have it as generic wheel too.

**Comment by icemac** [comment]
The next release will include one, it is now configured this way.

**Comment by dataflake** [comment]
I just finished version 1.6 and released source egg and wheel. It includes re-running meta/config to get the latest configuration and also adding support for Python 3.11 which seems safe here since it's a small package.
