### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/zope.globalrequest#7]
@davisagli @witsch Could one of you make a new release of this package?

Or add me (PyPi: hannosch) and Michael (PyPi: icemac) as additional owners?

The current master has rewritten tests, which no longer depend on zope.app.wsgi.

**Comment by davisagli** [comment]
@hannosch @icemac you are both owners now.

**Comment by icemac** [comment]
@davisagli Thank you.

**Comment by icemac** [comment]
Just released 1.4: https://pypi.org/project/zope.globalrequest/
